config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}

  resources :articles
  resources :tags, only: [:show]

  get 'healthcheck', to: 'health_checks#status'
  get 'fullcheck', to: 'health_checks#complete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  default_scope { order(date: :desc) }

  enum status: %i[wip published]

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  validates :content, presence: true
  validates :date, presence: true
  validates :slug, presence: true, slug: true, uniqueness: {case_sensitive: false}
  validates :title, presence: true

  paginates_per 5

  def to_param
    slug_changed? ? slug_was : slug
  end

  def tags_string=(string)
    self.tags = string.split(',').map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def tags_string
    tags.map(&:name).join(', ')
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :articles, through: :taggings

  validates :name, presence: true, uniqueness: {case_sensitive: false}

  def published_articles
    @published_articles ||= articles.published.decorate
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :validatable, :lockable

  validates :email, presence: true, email: true, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(_resource)
    articles_path
  end

  def after_sign_out_path_for(_resource)
    articles_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]

  def index
    authenticate_user! if status

    @articles = ArticlesFilter.run(status).page(page).decorate
  end

  def show
    authenticate_user! unless article.published?

    article
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new article_params

    if @article.save
      redirect_to @article
    else
      flash.now[:error] = error_message
      render :new
    end
  end

  def edit
    article
  end

  def update
    if article.update article_params
      redirect_to article
    else
      flash.now[:error] = error_message
      render :edit
    end
  end

  def destroy
    article.destroy
    redirect_to articles_url
  end

  private

  def error_message
    article.errors.full_messages.to_sentence
  end

  def article_params
    params.require(:article).permit(:title, :slug, :tags_string, :date, :status, :content)
  end

  def article
    @article ||= ArticleFinder.run params[:id]
  end

  def status
    @status ||= params[:status]
  end

  def page
    @page ||= params[:page]
  end
end

app/controllers/health_checks_controller.rb
class HealthChecksController < ApplicationController
  def status
    head :ok
  end

  def complete
    ActiveRecord::Base.connection.execute 'SELECT 1'

    head :ok
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_user_registered?, only: %i[new create]

  protected

  def one_user_registered?
    redirect_to new_user_session_path if User.count == 1
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title)
    "#{title} - Ralin Chimev".html_safe
  end

  def gravatar_url(email, size)
    gravatar = Digest::MD5.hexdigest(email).downcase
    "//gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  end
end

app/views/articles/_article.html.slim
li
  = time_tag article.date
  h2 = link_to article.title, article
  p = article.content_preview

app/views/articles/_article_footer.html.slim
footer = social_share_button_tag title

app/views/articles/_article_form.html.haml
= simple_form_for @article do |f|
  = f.input :title
  = f.input :slug
  = f.input :content, as: :text
  = f.input :status, collection: Article.statuses,
                     label_method: :first,
                     value_method: :first,
                     include_blank: false
  = f.button :submit, 'Save'

app/views/articles/_article_header.html.slim
header
  = link_to 'BACK', articles_path
  - if user_signed_in?
    = link_to 'EDIT', edit_article_path(article)
    = link_to 'DELETE', article, method: :delete

app/views/articles/_articles_footer.html.slim
.pagination
  = link_to_prev_page articles, '❮'
  = link_to_next_page articles, '❯'

app/views/articles/_articles_header.html.haml
%header
  = image_tag gravatar_url("ralin.chimev@gmail.com", 80), alt: t('brand')
  %h1= t('articles.header.title')
  .actions
    - if user_signed_in?
      = link_to t('articles.header.new').upcase, new_article_path
      = link_to t('articles.header.wip').upcase, articles_path(status: 'wip')
      = link_to t('articles.header.all').upcase, articles_path(status: 'all')
  .total
    = "#{t('articles.header.number_of_posts').upcase}: #{@articles.total_count}"

app/views/articles/_articles_header.html.slim
header
  = image_tag gravatar_url("ralin.chimev@gmail.com", 80), alt: t('brand')
  h1 = t 'articles.header.title'
  .actions
    - if user_signed_in?
      = link_to t('articles.header.new').upcase, new_article_path
      = link_to t('articles.header.wip').upcase, articles_path(status: 'wip')
      = link_to t('articles.header.all').upcase, articles_path(status: 'all')
  .total #{t('articles.header.count').upcase}: #{count}

app/views/articles/_tags.html.haml
.blog-tags
  - @article.tags.each do |tag|
    = link_to tag.name, tag_path(tag)

app/views/articles/edit.html.slim
- provide :title, @article.title

.blog-article
  header
    = link_to 'BACK', @article
  = render 'form'

app/views/articles/index.html.haml
- provide :title, t('.title')

.blog-articles
  = render 'articles_header'
  %ul
    = render @articles
  .pagination
    = link_to_prev_page @articles, '❮'
    = link_to_next_page @articles, '❯'

app/views/articles/index.html.slim
- provide :title, t('.title')

.blog-articles
  = render partial: 'articles_header', locals: {count: @articles.total_count}
  ul = render @articles
  = render partial: 'articles_footer', locals: {articles: @articles}

app/views/articles/new.html.haml
- provide :title, t('articles.header.new')

.blog-article
  %header
    = link_to 'BACK', articles_path
  = render 'form'

app/views/articles/new.html.slim
- provide :title, t('articles.header.new')

.blog-article
  header
    = link_to 'BACK', articles_path
  = render 'form'

app/views/articles/show.html.haml
- provide :title, @article.title

.blog-article
  %header
    = link_to 'BACK', articles_path
    - if user_signed_in?
      = link_to 'EDIT', edit_article_path(@article)
      = link_to 'DELETE', @article, method: :delete

  %article
    %h1= @article.title
    = render partial: 'tags'
    ~ @article.markdown
    %footer
      = social_share_button_tag(@article.title)

= render partial: 'comments'

app/views/home/show.html.haml
- provide :title, t('.title')

.panel
  %h1= t('.header')
  %p= t('.text')

app/views/layouts/_flash_messages.html.slim
.flash-messages
  - flash.each do |name, message|
    div class="flash-#{name}" #{message}

app/views/layouts/_footer.html.slim
footer.footer
  .container
    p == t 'footer.text'

app/views/layouts/_navbar.html.haml
%nav.navbar
  .container
    %span.fa.fa-beer
    = link_to t('brand'), root_path, class: 'brand'
    = link_to t('nav.home'), root_path
    = link_to t('nav.about'), page_path('about')
    = link_to t('nav.blog'), articles_path
    - if user_signed_in?
      = link_to t('nav.logout'), destroy_user_session_path, method: :delete
    - else
      = link_to t('nav.login'), new_user_session_path

app/views/layouts/_navbar.html.slim
nav.navbar
  .container
    span.fa.fa-beer
    = link_to t('brand'), root_path, class: 'brand'
    = link_to t('nav.home'), root_path
    = link_to t('nav.about'), page_path('about')
    = link_to t('nav.blog'), articles_path
    - if user_signed_in?
      = link_to t('nav.logout'), destroy_user_session_path, method: :delete
    - else
      = link_to t('nav.login'), new_user_session_path

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset='utf-8'
    meta http-equiv='X-UA-Compatible' content='IE=edge'
    meta name='viewport' content='width=device-width initial-scale=1'
    meta name='author' content='Ralin Chimev'
    title= page_title yield(:title)
    = favicon_link_tag 'favicon.png', type: 'image/png'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application', async: Rails.env.production?
    = csrf_meta_tags
  body
    - if current_page? root_path
      .home-hello
        = render 'layouts/navbar'
        .container
          = yield
    - else
      = render 'layouts/navbar'
      .container
        = render 'layouts/flash_messages'
        = yield
      = render 'layouts/footer'

app/views/pages/_feature.html.slim
li.about-feature
  .image
    span class="fa fa-#{feature[:icon]}"
  .text
    = link_to feature[:link] do
      h2 = feature[:title]
    p = feature[:text]

app/views/pages/about.html.haml
- provide :title, t('.title')

%h1= t '.title'

.about-overview
  .image
    = image_tag 'ralin.jpg', alt: 'Ralin Chimev'
  .text
    %p= t '.overview'
    %p= t '.blog-overview', years: Time.current.year - 1999

.about-features
  %ul
    = render partial: 'pages/feature', collection: t('.features'), as: :feature

.about-social
  %h2= t '.contact'
  .links
    = link_to icon('github'), 'https://github.com/ralinc', target: '_blank'
    = link_to icon('linkedin'), 'https://www.linkedin.com/in/ralinchimev', target: '_blank'
    = link_to icon('facebook'), 'https://facebook.com/ralin.chimev', target: '_blank'
    = link_to icon('envelope-o'), 'mailto:ralin.chimev@gmail.com'

app/views/pages/about.html.slim
- provide :title, t('.title')

h1 = t '.title'

.about-overview
  .image
    = image_tag 'ralin.jpg', alt: 'Ralin Chimev'
  .text
    p = t '.overview'
    p = t '.blog-overview', years: Time.current.year - 1999

.about-features
  ul = render partial: 'pages/feature', collection: t('.features'), as: :feature

.about-social
  h2 = t '.contact'
  .links
    = link_to icon('github'), 'https://github.com/ralinc', target: '_blank'
    = link_to icon('linkedin'), 'https://www.linkedin.com/in/ralinchimev', target: '_blank'
    = link_to icon('facebook'), 'https://facebook.com/ralin.chimev', target: '_blank'
    = link_to icon('envelope-o'), 'mailto:ralin.chimev@gmail.com'

app/views/pages/home.html.haml
- provide :title, t('.title')

.panel
  %h1= t('.header')
  %p= t('.text')

app/views/pages/home.html.slim
- provide :title, t('.title')

.panel
  h1 = t '.header'
  p = t '.text'

app/views/tags/_tags_header.html.slim
header
  h1 = @tag.name
  .actions
    = link_to 'BACK', :back
  .total #{t('articles.header.count').upcase}: #{articles_count}

app/views/tags/show.html.haml
- provide :title, t('articles.index.title')

.blog-articles
  %header
    %h1= @tag.name
    .actions
      = link_to 'BACK', :back
    .total
      = "#{t('articles.header.number_of_posts').upcase}: #{@tag.articles.published.size}"
  %ul
    = render @tag.articles.published

app/views/tags/show.html.slim
- provide :title, t('articles.index.title')

.blog-articles
  = render partial: 'tags_header', locals: {name: @tag.name, articles_count: @tag.published_articles.size}
  ul
    = render @tag.published_articles